language: rust
sudo: false
cache: cargo
os:
  - linux
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: stable
      env: BUILD_FMT=1
before_script:
 - if [ -n "$BUILD_FMT" ]; then rustup component add rustfmt-preview; fi
script:
- |
   if [ -n "$BUILD_FMT" ]; then
     cargo fmt -- --check
   else
     cargo check
   fi
